// app.js — Palworld UID Swap frontend controller.
//
// Orchestrates: file intake -> classify -> decompress + findGuidSlots -> map
// UIDs -> patch every file -> re-compress -> download. All client-side.

import {
  parseSavHeader, decompressSav, findGuidSlots, patchGuids, buildSav,
} from './palsav.js';
import codec from './codec-browser.js';

// ---------------------------------------------------------------------------
// DOM handles
// ---------------------------------------------------------------------------
const $ = (id) => document.getElementById(id);
const dropzone   = $('dropzone');
const levelInput = $('levelInput');
const playerInput = $('playerInput');
const levelErrEl = $('levelErr');
const playerErrEl = $('playerErr');
const fileListEl = $('fileList');
const mapSection = $('mapSection');
const mapToolsEl = $('mapTools');
const bannersEl  = $('banners');
const mapRowsEl  = $('mapRows');
const deploySection = $('deploySection');
const swapBtn    = $('swapBtn');
const resultsEl  = $('results');

// ---------------------------------------------------------------------------
// State
// ---------------------------------------------------------------------------
/** @type {Map<string, FileEntry>} keyed by lowercased filename */
const files = new Map();
let idSeq = 0;

const HOST_UID = '00000000-0000-0000-0000-000000000001';
const IGNORED = {
  'levelmeta.sav': 'World metadata, regenerated by the game. No player UIDs inside.',
  'localdata.sav': 'Per-machine data (map fog, fast-travel unlocks, markers). No UIDs inside. Each player keeps their own.',
  'worldoption.sav': 'World settings only. No player UIDs inside.',
};

// ---------------------------------------------------------------------------
// UUID helpers
// ---------------------------------------------------------------------------
const isPlayerName = (name) => /^[0-9a-fA-F]{32}\.sav$/.test(name);
const cleanHex = (s) => s.toLowerCase().replace(/[^0-9a-f]/g, '').slice(0, 32);
const hexToDashed = (h) =>
  `${h.slice(0, 8)}-${h.slice(8, 12)}-${h.slice(12, 16)}-${h.slice(16, 20)}-${h.slice(20, 32)}`;
const filenameToUuid = (name) => hexToDashed(name.replace(/\.sav$/i, '').toLowerCase());
const dashedToFileName = (dashed) => dashed.replace(/-/g, '').toUpperCase() + '.sav';

function fmtSize(n) {
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`;
  return `${(n / 1024 / 1024).toFixed(2)} MB`;
}

const BADGE = {
  PlM: { cls: 'plm', label: 'PlM · Oodle' },
  PlZ: { cls: 'plz', label: 'PlZ · zlib' },
  CNK: { cls: 'cnk', label: 'CNK · zlib' },
};

const uidHtml = (dashed) => dashed;

function friendlyError(err) {
  const m = (err && err.message) || String(err);
  if (/magic|too small to parse|inner magic/i.test(m)) {
    return 'Not a standard .sav container. Xbox / Game Pass saves are wrapped in a different container and .zip archives are not supported. Export a raw Level.sav / Players/*.sav from a Steam/PC save first.';
  }
  if (/Unknown type/i.test(m)) {
    return 'The parser hit a property it does not recognise. This save may be from a much newer or older Palworld version. Please file an issue on GitHub with your game version.';
  }
  return m;
}

// ---------------------------------------------------------------------------
// Intake
// ---------------------------------------------------------------------------
/**
 * @typedef {Object} FileEntry
 * @property {number} id
 * @property {string} name
 * @property {number} size
 * @property {Uint8Array} u8
 * @property {'level'|'player'} kind
 * @property {'parsing'|'ready'|'error'} status
 */

// Reason a file was rejected at intake, phrased for inline display.
function rejectReason(name) {
  const lower = name.toLowerCase();
  if (lower === 'level.sav') return `${name}: this is the world file — use the "Choose Level.sav" picker above.`;
  if (IGNORED[lower]) return `${name}: ${IGNORED[lower]} Not a player save.`;
  return `${name}: not a player save. Player files are named <32 hex characters>.sav.`;
}

// Render a transient list of rejection messages under one control.
function showErrors(el, messages) {
  el.replaceChildren();
  for (const m of messages) {
    const d = document.createElement('div');
    d.className = 'fc-note err';
    d.textContent = m;
    el.appendChild(d);
  }
}

// Read one file, build its entry (replacing any prior file of the same name),
// parse it, and refresh the mapping.
async function ingest(file, kind) {
  const lower = file.name.toLowerCase();
  const buf = new Uint8Array(await file.arrayBuffer());
  const entry = {
    id: ++idSeq, name: file.name, size: file.size, u8: buf,
    kind, status: 'parsing', error: null,
    header: null, gvas: null, slots: null, warnings: [],
    format: null, saveType: null, fileUid: null, uidInFile: false,
    target: '',
  };
  if (kind === 'player') entry.fileUid = filenameToUuid(file.name);
  files.set(lower, entry); // replace any prior file with the same name
  renderFiles();
  await processEntry(entry);
  rebuildMapping();
}

// Level.sav picker: exactly one file, must be named Level.sav.
async function addLevelFile(file) {
  levelErrEl.replaceChildren();
  if (file.name.toLowerCase() !== 'level.sav') {
    showErrors(levelErrEl, [`This picker is only for Level.sav, you selected ${file.name}`]);
    return;
  }
  await ingest(file, 'level'); // same map key replaces any prior Level.sav
}

// Player-saves picker: each file must be a 32-hex-char UID name.
async function addPlayerFiles(fileList) {
  playerErrEl.replaceChildren();
  const errs = [];
  for (const file of fileList) {
    if (isPlayerName(file.name)) await ingest(file, 'player');
    else errs.push(rejectReason(file.name));
  }
  if (errs.length) showErrors(playerErrEl, errs);
}

// Shared drop target: route each dropped file by name, same rules as the pickers.
async function addDropped(fileList) {
  levelErrEl.replaceChildren();
  playerErrEl.replaceChildren();
  const errs = [];
  for (const file of fileList) {
    if (file.name.toLowerCase() === 'level.sav') await ingest(file, 'level');
    else if (isPlayerName(file.name)) await ingest(file, 'player');
    else errs.push(rejectReason(file.name));
  }
  if (errs.length) showErrors(playerErrEl, errs);
}

async function processEntry(entry) {
  try {
    entry.header = parseSavHeader(entry.u8);
    entry.format = entry.header.format;
    const { gvas, format, saveType } = await decompressSav(entry.u8, codec);
    entry.gvas = gvas; entry.format = format; entry.saveType = saveType;
    const { slots, warnings } = findGuidSlots(gvas);
    entry.slots = slots; entry.warnings = warnings;
    if (entry.kind === 'player') {
      entry.uidInFile = slots.some((s) => s.uuid === entry.fileUid);
    }
    entry.status = 'ready';
  } catch (err) {
    entry.status = 'error';
    entry.error = friendlyError(err);
  }
  renderFiles();
}

function removeEntry(id) {
  for (const [k, e] of files) if (e.id === id) { files.delete(k); break; }
  renderFiles();
  rebuildMapping();
}

// ---------------------------------------------------------------------------
// Render: file cards
// ---------------------------------------------------------------------------
function renderFiles() {
  fileListEl.replaceChildren();
  // Order: level first, then players.
  const order = { level: 0, player: 1 };
  const list = [...files.values()].sort((a, b) => order[a.kind] - order[b.kind] || a.name.localeCompare(b.name));

  for (const e of list) {
    const card = document.createElement('div');
    card.className = 'file-card slide-in' + (e.status === 'error' ? ' err' : '');

    const iconCls = e.kind === 'level' ? 'level' : 'player';
    const iconTxt = e.kind === 'level' ? 'LVL' : 'PLYR';

    const badge = e.format && BADGE[e.format]
      ? `<span class="badge ${BADGE[e.format].cls}">${BADGE[e.format].label}</span>` : '';

    let statusHtml = '';
    if (e.status === 'parsing') statusHtml = `<span>reading…</span>`;
    else if (e.status === 'error') statusHtml = `<span class="st-err">✕ error</span>`;
    else if (e.kind === 'player' && !e.uidInFile) statusHtml = `<span class="st-warn">⚠ UID not found</span>`;
    else statusHtml = `<span class="st-ok">✓ ${e.slots ? e.slots.length : 0} slots</span>`;

    let noteHtml = '';
    if (e.status === 'error') noteHtml = `<div class="fc-note err">${escapeHtml(e.error)}</div>`;
    else if (e.kind === 'player' && e.status === 'ready' && !e.uidInFile)
      noteHtml = `<div class="fc-note warn">The filename UID <code>${e.fileUid}</code> was not found among this file's GUID slots. Double-check it's the right Players file.</div>`;
    else if (e.warnings && e.warnings.length)
      noteHtml = `<div class="fc-note warn">${e.warnings.length} parser warning(s): some blobs were skipped.</div>`;

    card.innerHTML =
      `<div class="fc-icon ${iconCls}">${iconTxt}</div>` +
      `<div class="fc-main">` +
        `<div class="fc-name">${escapeHtml(e.name)}</div>` +
        `<div class="fc-sub">${fmtSize(e.size)} ${badge}</div>` +
      `</div>` +
      `<div class="fc-status">${statusHtml}</div>` +
      `<button class="fc-remove" title="Remove" aria-label="Remove ${escapeHtml(e.name)}">×</button>` +
      noteHtml;

    card.querySelector('.fc-remove').addEventListener('click', () => removeEntry(e.id));
    fileListEl.appendChild(card);
  }
}

function escapeHtml(s) {
  return String(s).replace(/[&<>"']/g, (c) =>
    ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}

// ---------------------------------------------------------------------------
// Mapping section
// ---------------------------------------------------------------------------
const readyPlayers = () => [...files.values()].filter((e) => e.kind === 'player' && e.status === 'ready');
const inputEls = new Map(); // entry.id -> <input>

function rebuildMapping() {
  const players = readyPlayers();
  if (players.length === 0) {
    mapSection.classList.add('is-hidden');
    deploySection.classList.add('is-hidden');
    return;
  }
  mapSection.classList.remove('is-hidden');
  deploySection.classList.remove('is-hidden');

  // Tools ---------------------------------------------------------------
  mapToolsEl.replaceChildren();
  if (players.length === 2) {
    const swap = mkBtn('⇄ Swap these two', 'btn btn-primary btn-swap', () => {
      const [a, b] = players;
      setTarget(a, b.fileUid);
      setTarget(b, a.fileUid);
      validate();
    });
    mapToolsEl.appendChild(swap);
  }
  mapToolsEl.appendChild(mkBtn('Reset', 'btn btn-ghost', () => {
    for (const e of players) setTarget(e, '');
    validate();
  }));

  // Rows ----------------------------------------------------------------
  mapRowsEl.replaceChildren();
  inputEls.clear();
  for (const e of players) {
    const row = document.createElement('div');
    row.className = 'map-row slide-in';
    row.dataset.id = String(e.id);

    row.innerHTML =
      `<div class="mr-head">` +
        `<span class="mr-file">${escapeHtml(e.name)}</span>` +
        `<button class="btn btn-ghost mr-hostbtn" type="button">Make host</button>` +
      `</div>` +
      `<div class="mr-flow">` +
        `<div class="uid-from"><div class="uid-label">Current UID</div>` +
          `<div class="uid-display">${uidHtml(e.fileUid)}</div></div>` +
        `<div class="arrow" aria-hidden="true">→</div>` +
        `<div class="uid-to"><div class="uid-label">New UID</div>` +
          `<input class="uid-input" type="text" spellcheck="false" autocomplete="off" ` +
            `maxlength="36" placeholder="unchanged" ` +
            `aria-label="New UID for ${escapeHtml(e.name)}" value="${e.target}" /></div>` +
      `</div>` +
      `<div class="mr-msg"></div>`;

    const input = row.querySelector('.uid-input');
    inputEls.set(e.id, input);
    input.addEventListener('input', () => {
      const caretEnd = input.selectionStart === input.value.length;
      const hex = cleanHex(input.value);
      // Re-format progressively: insert dashes only up to typed length.
      input.value = formatHexProgressive(hex);
      if (caretEnd) input.setSelectionRange(input.value.length, input.value.length);
      e.target = input.value;
      validate();
    });

    row.querySelector('.mr-hostbtn').addEventListener('click', () => {
      // Free the host UID from any other row that currently holds it.
      for (const other of players) {
        if (other === e) continue;
        if (cleanHex(other.target) === cleanHex(HOST_UID) && cleanHex(other.target).length === 32) {
          setTarget(other, e.fileUid);
        }
      }
      setTarget(e, HOST_UID);
      validate();
    });

    mapRowsEl.appendChild(row);
  }
  validate();
}

function mkBtn(label, cls, onClick) {
  const b = document.createElement('button');
  b.type = 'button'; b.className = cls; b.textContent = label;
  b.addEventListener('click', onClick);
  return b;
}

function setTarget(entry, dashedOrHex) {
  const hex = cleanHex(dashedOrHex);
  entry.target = hex.length === 32 ? hexToDashed(hex) : formatHexProgressive(hex);
  const input = inputEls.get(entry.id);
  if (input) input.value = entry.target;
}

// Progressive dashed formatting for partial input (8-4-4-4-12).
function formatHexProgressive(hex) {
  const cuts = [8, 12, 16, 20];
  let out = '';
  for (let i = 0; i < hex.length; i++) {
    if (cuts.includes(i)) out += '-';
    out += hex[i];
  }
  return out;
}

// ---------------------------------------------------------------------------
// Validation — recomputes banners, row states, and enables/disables deploy.
// ---------------------------------------------------------------------------
let currentMapping = new Map();

function validate() {
  const players = readyPlayers();
  const existing = new Set(players.map((p) => p.fileUid)); // known identities
  const rows = [];

  for (const e of players) {
    const rowEl = mapRowsEl.querySelector(`.map-row[data-id="${e.id}"]`);
    const input = inputEls.get(e.id);
    const msgEl = rowEl ? rowEl.querySelector('.mr-msg') : null;
    const hex = cleanHex(e.target);
    let state = 'unchanged', target = null;

    if (hex.length === 0) state = 'unchanged';
    else if (hex.length !== 32) state = 'incomplete';
    else {
      target = hexToDashed(hex);
      state = target === e.fileUid ? 'unchanged' : 'active';
    }
    rows.push({ e, target, state, rowEl, input, msgEl });
    if (input) input.classList.remove('invalid', 'valid');
  }

  // Duplicate active targets -> error.
  const targetCounts = {};
  for (const r of rows) if (r.state === 'active') targetCounts[r.target] = (targetCounts[r.target] || 0) + 1;

  const sources = new Set(rows.filter((r) => r.state === 'active').map((r) => r.e.fileUid));
  const collisions = new Set();
  let hasError = false;

  const mapping = new Map();
  for (const r of rows) {
    let msg = '', cls = '';
    if (r.state === 'incomplete') {
      cls = 'err'; msg = 'Needs 32 hex characters.'; hasError = true;
      if (r.input) r.input.classList.add('invalid');
    } else if (r.state === 'active') {
      if (targetCounts[r.target] > 1) {
        cls = 'err'; msg = 'Duplicate target: two players cannot get the same UID.'; hasError = true;
        if (r.input) r.input.classList.add('invalid');
      } else {
        if (r.input) r.input.classList.add('valid');
        cls = 'ok'; msg = `→ ${dashedToFileName(r.target)}`;
        mapping.set(r.e.fileUid, r.target);
        // Collision: target already belongs to an identity not being remapped.
        if (existing.has(r.target) && !sources.has(r.target)) collisions.add(r.target);
      }
    } else {
      msg = 'unchanged, skipped'; cls = '';
    }
    if (r.rowEl) r.rowEl.classList.toggle('bad', cls === 'err');
    if (r.msgEl) { r.msgEl.textContent = msg; r.msgEl.className = 'mr-msg ' + cls; }
  }

  // Banners -------------------------------------------------------------
  bannersEl.replaceChildren();
  if (hasError) {
    addBanner('err', 'Fix the highlighted rows', 'Some target UIDs are duplicated or incomplete. Nothing will be written until these are resolved.');
  }
  for (const c of collisions) {
    addBanner('warn', 'Possible collision',
      `Target UID ${c} already belongs to a player who is not being re-IDed. Two owners will share this identity. Usually you also want to remap that player.`);
  }

  currentMapping = hasError ? new Map() : mapping;
  swapBtn.disabled = hasError || mapping.size === 0;
  swapBtn.textContent = mapping.size === 0 ? 'Swap IDs' : `Swap IDs (${mapping.size} player${mapping.size > 1 ? 's' : ''})`;
}

function addBanner(kind, title, body) {
  const b = document.createElement('div');
  b.className = 'banner ' + kind;
  b.innerHTML = `<span class="bi">${kind === 'err' ? '✕' : '⚠'}</span><span><b>${escapeHtml(title)}.</b> ${escapeHtml(body)}</span>`;
  bannersEl.appendChild(b);
}

// ---------------------------------------------------------------------------
// Deploy — patch every accepted file, rebuild, offer downloads.
// ---------------------------------------------------------------------------
async function deploy() {
  if (currentMapping.size === 0) return;
  // Snapshot: validate() reassigns currentMapping on input events, which can
  // fire while buildSav awaits mid-loop.
  const mapping = new Map(currentMapping);
  swapBtn.disabled = true;
  const original = swapBtn.textContent;
  swapBtn.textContent = 'Working…';
  resultsEl.replaceChildren();

  const accepted = [...files.values()].filter(
    (e) => (e.kind === 'level' || e.kind === 'player') && e.status === 'ready' && e.gvas,
  );
  const outputs = [];

  // Patch fresh clones so re-runs stay clean and the cached gvas is untouched.
  const clones = new Map();
  for (const e of accepted) clones.set(e, e.gvas.slice());

  try {
    for (const e of accepted) {
      const clone = clones.get(e);
      const { patched } = patchGuids(clone, e.slots, mapping);
      const bytes = await buildSav(clone, { format: e.format, saveType: e.saveType }, codec);

      const outName = e.kind === 'player'
        ? dashedToFileName(mapping.get(e.fileUid) || e.fileUid)
        : e.name;

      outputs.push({ name: outName, bytes });
      renderResult(e, outName, bytes, patched);
      await new Promise((r) => setTimeout(r, 0));
    }

    if (outputs.length > 1) {
      const actions = document.createElement('div');
      actions.className = 'results-actions';
      actions.appendChild(mkBtn(`Download all (.zip) · ${outputs.length} files`, 'btn btn-primary', () => {
        const zip = buildZip(outputs);
        triggerDownload('palworld-uid-swap.zip', zip);
      }));
      resultsEl.appendChild(actions);
    }
  } catch (err) {
    addResultError(friendlyError(err));
  } finally {
    swapBtn.disabled = false;
    swapBtn.textContent = original;
  }
}

function renderResult(entry, outName, bytes, patched) {
  const warned = entry.warnings && entry.warnings.length;
  const card = document.createElement('div');
  card.className = 'result-card slide-in' + (warned ? ' has-warn' : '');

  const patchedKeys = Object.keys(patched);
  const detail = patchedKeys.length
    ? patchedKeys.map((uid) => `<span class="k">${patched[uid]}</span> GUID(s) with <code>${uid}</code>`).join(' · ')
    : 'no matching UIDs in this file (left unchanged, re-compressed)';

  card.innerHTML =
    `<div class="rc-name">${escapeHtml(outName)}</div>` +
    `<div></div>` +
    `<div class="rc-detail">Patched: ${detail} (${fmtSize(bytes.length)})</div>` +
    (warned ? `<div class="rc-warn">⚠ ${entry.warnings.length} parser warning(s): some blob was skipped, so some references may not have been updated. Verify in-game.</div>` : '');

  const dlWrap = card.children[1];
  const dl = mkBtn('Download', 'btn btn-primary', () => triggerDownload(outName, bytes));
  dlWrap.appendChild(dl);
  resultsEl.appendChild(card);
}

function addResultError(msg) {
  const b = document.createElement('div');
  b.className = 'banner err';
  b.innerHTML = `<span class="bi">✕</span><span><b>Failed.</b> ${escapeHtml(msg)}</span>`;
  resultsEl.appendChild(b);
}

function triggerDownload(name, bytes) {
  const blob = new Blob([bytes], { type: 'application/octet-stream' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = name;
  document.body.appendChild(a); a.click(); a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 4000);
}

// ---------------------------------------------------------------------------
// Minimal STORE-only ZIP writer (no compression, no dependency).
// ---------------------------------------------------------------------------
const CRC_TABLE = (() => {
  const t = new Uint32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c >>> 0;
  }
  return t;
})();
function crc32(u8) {
  let c = 0xffffffff;
  for (let i = 0; i < u8.length; i++) c = CRC_TABLE[(c ^ u8[i]) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

/** @param {{name:string, bytes:Uint8Array}[]} entries */
function buildZip(entries) {
  const enc = new TextEncoder();
  const locals = [];
  const centrals = [];
  let offset = 0;

  for (const { name, bytes } of entries) {
    const nameBytes = enc.encode(name);
    const crc = crc32(bytes);
    const size = bytes.length;

    // Local file header (30 bytes + name) + data.
    const lh = new Uint8Array(30 + nameBytes.length);
    const ldv = new DataView(lh.buffer);
    ldv.setUint32(0, 0x04034b50, true);   // signature
    ldv.setUint16(4, 20, true);           // version needed
    ldv.setUint16(6, 0, true);            // flags
    ldv.setUint16(8, 0, true);            // method 0 = store
    ldv.setUint16(10, 0, true);           // mod time
    ldv.setUint16(12, 0x21, true);        // mod date (valid, arbitrary)
    ldv.setUint32(14, crc, true);
    ldv.setUint32(18, size, true);        // compressed size
    ldv.setUint32(22, size, true);        // uncompressed size
    ldv.setUint16(26, nameBytes.length, true);
    ldv.setUint16(28, 0, true);           // extra len
    lh.set(nameBytes, 30);

    locals.push(lh, bytes);

    // Central directory header (46 bytes + name).
    const ch = new Uint8Array(46 + nameBytes.length);
    const cdv = new DataView(ch.buffer);
    cdv.setUint32(0, 0x02014b50, true);
    cdv.setUint16(4, 20, true);           // version made by
    cdv.setUint16(6, 20, true);           // version needed
    cdv.setUint16(8, 0, true);
    cdv.setUint16(10, 0, true);
    cdv.setUint16(12, 0, true);
    cdv.setUint16(14, 0x21, true);
    cdv.setUint32(16, crc, true);
    cdv.setUint32(20, size, true);
    cdv.setUint32(24, size, true);
    cdv.setUint16(28, nameBytes.length, true);
    cdv.setUint16(30, 0, true);           // extra
    cdv.setUint16(32, 0, true);           // comment
    cdv.setUint16(34, 0, true);           // disk
    cdv.setUint16(36, 0, true);           // internal attrs
    cdv.setUint32(38, 0, true);           // external attrs
    cdv.setUint32(42, offset, true);      // local header offset
    ch.set(nameBytes, 46);
    centrals.push(ch);

    offset += lh.length + size;
  }

  const centralSize = centrals.reduce((s, c) => s + c.length, 0);
  const centralOffset = offset;

  const eocd = new Uint8Array(22);
  const edv = new DataView(eocd.buffer);
  edv.setUint32(0, 0x06054b50, true);
  edv.setUint16(4, 0, true);
  edv.setUint16(6, 0, true);
  edv.setUint16(8, entries.length, true);
  edv.setUint16(10, entries.length, true);
  edv.setUint32(12, centralSize, true);
  edv.setUint32(16, centralOffset, true);
  edv.setUint16(20, 0, true);

  const total = offset + centralSize + eocd.length;
  const out = new Uint8Array(total);
  let p = 0;
  for (const part of locals) { out.set(part, p); p += part.length; }
  for (const part of centrals) { out.set(part, p); p += part.length; }
  out.set(eocd, p);
  return out;
}

// ---------------------------------------------------------------------------
// Wiring
// ---------------------------------------------------------------------------
levelInput.addEventListener('change', () => {
  if (levelInput.files && levelInput.files.length) addLevelFile(levelInput.files[0]);
  levelInput.value = '';
});
playerInput.addEventListener('change', () => {
  if (playerInput.files && playerInput.files.length) addPlayerFiles(playerInput.files);
  playerInput.value = '';
});

['dragenter', 'dragover'].forEach((ev) =>
  dropzone.addEventListener(ev, (e) => { e.preventDefault(); dropzone.classList.add('drag'); }));
['dragleave', 'dragend'].forEach((ev) =>
  dropzone.addEventListener(ev, (e) => { e.preventDefault(); if (e.target === dropzone) dropzone.classList.remove('drag'); }));
dropzone.addEventListener('drop', (e) => {
  e.preventDefault();
  dropzone.classList.remove('drag');
  if (e.dataTransfer && e.dataTransfer.files.length) addDropped(e.dataTransfer.files);
});
// Prevent the browser from navigating when a file is dropped outside the zone.
window.addEventListener('dragover', (e) => e.preventDefault());
window.addEventListener('drop', (e) => e.preventDefault());

swapBtn.addEventListener('click', deploy);
